// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Todo struct {
	ID        int    `json:"ID"`
	Title     string `json:"Title"`
	Completed bool   `json:"Completed"`
}
